project:
  type: book
  output-dir: docs
  
book:
  favicon: images/random_walk.png
  title: "Stochastic Processes with R"
  chapters:
    - index.qmd
    - compound_poisson.qmd
    - conditional_poisson.qmd
    - birth_and_death.qmd
    - branching_process.qmd
    - hmm.qmd

format:
  html: 
    theme: cosmo
    cover-image: images/random_walk.png
    code-link: true
