project:
  type: book
  output-dir: docs
  
book:
  title: "Stochastic Processes with R"
  chapters:
    - index.qmd
    - compound_poisson.qmd

format:
  html: 
    theme: cosmo
    cover-image: images/random_walk.png
    code-link: true

